export function getPersonRecordByID(id) {
  const searchResult = {
    role: "Faculty",
    personalInformation: {
      namePrefix: "",
      firstName: "Bradley",
      middleName: "Joshua",
      lastName: "Dexter",
      suffix: "Ph.D.",
      name: "Bradley Dexter",
      preferredName: "None",
      maidenName: "None",
      title: "Professor",
      image: "Bradley2.png",
      department: "College of Business",
      age: "69",
      alternateId: "None",
      ssn: "***-**-2222",
      alienId: "None",
      birthDate: "1975-12-18",
      gender: "Male",
      maritalStatus: "Married",
      citizenship: "United States",
      nationality: "American",
      ethnicity1: "European American",
      ethnicity2: "None",
      race1: "White",
      race2: "None",
      veteranStatus: "No",
      militaryBranch: "None",
      disability: "None",
      accommodation: "None",
      personalMessage: "",
      onlineStatus: "",
      timezone: "",
    },
    communicationPreferences: {
      languages: [],
      primaryLanguage: "English",
      secondaryLanguage: "Spanish",
      tertiaryLanguage: "None",
      emailAddress: "bdexter@ahead.edu",
      phoneNumbers: [],
      officePhone: "555-432-1100",
      mobilePhone: "",
      url: "https://www.ahea.edu/about-ahea/college-of-business/bdexter",
      receiveSMS: false,
    },
    contactInformation: {
      primary: {
        streetAddress: "1000 Education Way",
        city: "Carlisle",
        state: "Iowa",
        postalCode: "50047",
        county: "Warren",
        country: "United States",
        mailName: "Bradley Dexter",
        phoneNumber: "555-432-1122",
        phoneNumberType: "Mobile",
        emailAddress: "bdexter@ahea.edu",
        emailAddressType: "Work",
      },
      secondary: {
        streetAddress: "",
        city: "",
        state: "",
        postalCode: "",
        county: "",
        country: "",
        mailName: "",
        phoneNumber: "",
        phoneNumberType: "",
        emailAddress: "bdexter@gmail.com",
        emailAddressType: "Personal",
      },
    },
    emergencyContacts: {
      primary: {
        name: "Beatrice Dexter",
        relationship: "Spouse",
        streetAddress: "1010 Reliance Lane",
        city: "Des Moines",
        state: "Iowa",
        postalCode: "50048",
        county: "Carlisle",
        country: "United States",
        phoneNumber: "555-432-1123",
        phoneNumberType: "Mobile",
        emailAddress: "ldexter@gmail.com",
        emailAddressType: "Personal",
      },
      secondary: {
        name: "Timothy Dexter",
        relationship: "Sibling",
        streetAddress: "1010 Reliance Lane",
        city: "Des Moines",
        state: "Iowa",
        postalCode: "50048",
        county: "Carlisle",
        country: "United States",
        phoneNumber: "555-432-2345",
        phoneNumberType: "Mobile",
        emailAddress: "tdexter@gmail.com",
        emailAddressType: "Personal",
      },
    },
    credentials: {
      educationLevel: "Doctorate",
      degrees: [
        {
          name: "Bachelor's",
          discipline: "Business",
          institution: "AHEA University",
          graduationYear: "1984",
        },
        {
          name: "Master's",
          discipline: "Business",
          institution: "Lehigh University",
          graduationYear: "1987",
        },
        {
          name: "Doctorate",
          discipline: "Economics",
          institution: "Grove City College",
          graduationYear: "1994",
        },
      ],
      additionalGraduateHours: [
        {
          areaOfStudy: "",
          institution: "",
          numberOfHours: "",
        },
        {
          areaOfStudy: "",
          institution: "",
          numberOfHours: "",
        },
      ],
      certificates: [
        {
          name: "",
          institution: "",
          numberofHours: "",
        },
        {
          name: "",
          institution: "",
          numberofHours: "",
        },
      ],
      certifications: [
        {
          name: "",
          governingBody: "",
          numberOfHours: "",
        },
        {
          name: "",
          governingBody: "",
          numberOfHours: "",
        },
      ],
    },
  };

  return searchResult;
}
